### ISSUE TITLE
Weird Zeroes

### ISSUE THREAD

**Issue by tamalCodes** [utkarsh1311/interactive-card-component#2]
### There are some weird zeroes

![image](https://user-images.githubusercontent.com/72851613/186437347-855acad3-9c07-44d3-8e7d-cedf98cb9583.png)

If you'd randomly select throughout the screen - there are some zeroes on the screen.
These are just beside the `CONFIRM` button.

**Comment by utkarsh1311** [comment]
Thank you for pointing that out. Actually it's a responsiveness issue. I am trying to fix it for some other screen sizes.

**Comment by tamalCodes** [comment]
Aah i see, since it's already under-development i am closing the issue then !
